// Data for AI Agents Intensive landing
window.PROGRAM_DATA = {
  dates: {
    regOpen: "11 серпня 2026",
    regClose: "7 вересня 2026",
    weekStart: "14 вересня",
    weekEnd: "25 вересня",
    challengeStart: "28 вересня",
    challengeEnd: "9 жовтня",
    demoDay: "12 жовтня 2026",
  },
  facts: [
    { num: "3", suffix: "", label: "тижні від нуля до working AI-агента" },
    { num: "10", suffix: "", label: "відкритих лекцій від практиків Genesis-екосистеми" },
    { num: "3", suffix: "", label: "продуктових кейси Challenge від компаній" },
    { num: "1", suffix: "", label: "Demo Day з fast-track оффером" },
  ],
  audiences: [
    {
      n: "01",
      name: "Студентам IT",
      copy: "Отримай перший реальний AI-проєкт у портфоліо та fast-track до співбесід у Genesis-компаніях.",
    },
    {
      n: "02",
      name: "Junior-розробникам",
      copy: "Навчись будувати AI-агентів і vibecoding-прототипи, які вже завтра шиплять у продакшн.",
    },
    {
      n: "03",
      name: "Аналітикам та PM",
      copy: "Опануй AI-інструменти для прискорення продуктових рішень — від churn-прогнозів до синтезу інсайтів.",
    },
    {
      n: "04",
      name: "Початківцям",
      copy: "Отримай перший досвід у побудові AI-агентів та почни кар'єру у сфері продуктового IT.",
    },
  ],
  weekFoundations: [
    { n: "Day 01", title: "Що таке AI Agents — від chatbot до autonomous agent", speaker: "AI Lead · AMO / 6037" },
    { n: "Day 02", title: "No-code агенти — Make & Zapier за годину", speaker: "Practical session" },
    { n: "Day 03", title: "LLM API basics через vibecoding і Cursor", speaker: "Tech Lead · SKELAR" },
    { n: "Day 04", title: "Memory і tools — як агент «пам'ятає» і «діє»", speaker: "Senior Engineer · AMO" },
    { n: "Day 05", title: "Prompt engineering для агентів", speaker: "AI Practitioner" },
  ],
  weekApplied: [
    { n: "Day 06", title: "Retention Agent — кейс OBRIO / Boosters", speaker: "CPO · OBRIO" },
    { n: "Day 07", title: "Analytics AI — синтез відгуків та churn-сигнали", speaker: "Head of Analytics" },
    { n: "Day 08", title: "Vibecoding + Cursor для прототипів — live build", speaker: "Tech Lead · SKELAR" },
    { n: "Day 09", title: "Міні-прототип під менторством · розбір кейсів", speaker: "Mentors panel" },
    { n: "Day 10", title: "Q&A з менторами + prep до Challenge", speaker: "Project team" },
  ],
  cases: [
    {
      company: "OBRIO / Boosters",
      title: "Retention Agent",
      copy: "AI-агент, що прогнозує відтік у B2C mobile-аплікації та запускає персоналізований re-engagement у потрібний момент.",
      metric: "Retention D30",
      icon: "users",
    },
    {
      company: "AMO",
      title: "Analytics AI",
      copy: "Автоматизація продуктової аналітики: синтез user-відгуків, churn-сигнали, інсайти з A/B-тестів — без ручних дашбордів.",
      metric: "Time-to-insight",
      icon: "chart",
    },
    {
      company: "Universe Group",
      title: "Product Prototyper",
      copy: "Побудова MVP AI-фічі для реального продукту через vibecoding. Від ідеї до working demo за 10 днів.",
      metric: "Working MVP",
      icon: "spark",
    },
  ],
  outcomes: [
    { title: "Перший AI-агент", copy: "Власний working AI-агент для реальної продуктової задачі — від ідеї до прототипу.", icon: "agent" },
    { title: "Практичний досвід", copy: "Vibecoding і Claude API для вирішення реального кейсу Genesis-компанії.", icon: "code" },
    { title: "Проєкт у портфоліо", copy: "Готове AI-рішення, яке можна показати на будь-якій співбесіді в IT.", icon: "folder" },
    { title: "Менторська підтримка", copy: "Фідбек від практиків Genesis-екосистеми — людей, які будують AI-продукти щодня.", icon: "compass" },
    { title: "Нетворкінг", copy: "Однодумці та представники компаній Genesis-екосистеми на лекціях і Demo Day.", icon: "users2" },
    { title: "Шанс на оффер", copy: "Найкращі учасники отримають fast-track запрошення на співбесіди в IT-компанії Genesis.", icon: "rocket" },
  ],
  phases: [
    {
      n: "Phase 01",
      name: "Ініціація",
      dates: "10.06 — 10.07",
      tasks: "Дослідження, аудиторія, метрики, концепція, sign-off CGO",
      count: 6,
      owner: "Project Specialist",
    },
    {
      n: "Phase 02",
      name: "Планування",
      dates: "12.07 — 20.08",
      tasks: "10 лекцій, 3 кейси, критерії, форма, FAQ, шаблони",
      count: 7,
      owner: "Project Specialist",
    },
    {
      n: "Phase 03",
      name: "Набір + Week",
      dates: "07.09 — 25.09",
      tasks: "Закриття реєстрації, attendance, модерація 10 лекцій, відкриття Challenge",
      count: 5,
      owner: "Project Specialist",
    },
    {
      n: "Phase 04",
      name: "Challenge + Demo Day",
      dates: "28.09 — 12.10",
      tasks: "Kickoff, checkpoint, фінальні демо, журі, Demo Day",
      count: 7,
      owner: "Project + Mentors",
    },
    {
      n: "Phase 05",
      name: "Завершення",
      dates: "15.10 — 21.10",
      tasks: "Брифінг менторів, ретро, фінальні метрики програми",
      count: 3,
      owner: "Project Specialist",
    },
  ],
  risks: [
    {
      phase: "Ініціація",
      sub: "Концепція",
      risk: "KSE відмовляється від партнерства або затримує підтвердження",
      mitig: "Переговори за 8 тижнів через Genesis for Universities. Резервний університет — КМА / КПІ.",
      level: "med",
    },
    {
      phase: "Планування",
      sub: "Контент",
      risk: "Спікер відмовляється або зникає за 1-2 тижні до старту",
      mitig: "1-2 резервних спікери на кожен слот. Підтвердження всіх спікерів до 10.08.",
      level: "med",
    },
    {
      phase: "Маркетинг",
      sub: "Набір учасників",
      risk: "Менше 50 реєстрацій на Week",
      mitig: "Промо за 4 тижні. KSE-канал. Додаткова хвиля DOU + LinkedIn + платна реклама.",
      level: "high",
    },
    {
      phase: "Виконання",
      sub: "Челендж",
      risk: "Учасники не здають демо в дедлайн або слабкі результати",
      mitig: "Mid-check на Day 5 + нагадування на Day 8. Чіткі критерії заздалегідь.",
      level: "med",
    },
    {
      phase: "Demo Day",
      sub: "Журі / Оффери",
      risk: "Жоден учасник не отримує fast-track запрошення",
      mitig: "Узгоджена мінімальна планка з Talent Acquisition. Альтернатива — стажування або менторство.",
      level: "low",
    },
  ],
  riskSummary: [
    { num: 12, label: "ризиків ідентифіковано", sub: "у 6 фазах проєкту", cls: "" },
    { num: 2, label: "High-priority", sub: "з планом mitigation", cls: "high" },
    { num: 8, label: "Medium-priority", sub: "з превентивними діями", cls: "med" },
    { num: 2, label: "Low-priority", sub: "контрольовані фоном", cls: "low" },
  ],
  metrics: [
    { label: "Реєстрації на Week", target: "1500", em: "+", desc: "Включно з 500+ із KSE-каналу. Узгоджено з SoftServe AgentForge benchmark." },
    { label: "Attendance ≥3/10 лекцій", target: "60", em: "%", desc: "Учасники, що відвідали мінімум 3 лекції з 10 — поріг готовності до Challenge." },
    { label: "Заявки на Challenge", target: "300", em: "+", desc: "Учасники Week, що подалися на відбір. Conversion target ≈ 20%." },
    { label: "Прийнято на Challenge", target: "60", em: "", desc: "Когорта Challenge — індивідуальний формат. ~20% від заявок." },
    { label: "Завершені демо", target: "75", em: "%", desc: "Учасники Challenge, що здали working demo на Demo Day." },
    { label: "Fast-track оффери", target: "5", em: "+", desc: "Запрошення на співбесіди в Genesis-компанії після Demo Day." },
  ],
  faq: [
    {
      q: "Скільки коштує участь?",
      a: "Участь у Genesis AI Agents Intensive безоплатна — як і всі програми Genesis Academy. Це інвестиція Genesis в розвиток продуктового IT в Україні.",
    },
    {
      q: "Що треба для участі в Week (без відбору)?",
      a: "Реєстрація на сайті до 7 вересня, власний робочий ноутбук, базове розуміння англійської (читання документації). Усі лекції — українською.",
    },
    {
      q: "Що треба для участі в Challenge (з відбором)?",
      a: "Успішне проходження Week (відмічена присутність на ≥6 лекціях), заявка з мотиваційним листом і коротким описом релевантного досвіду, базове розуміння продуктового IT. Перевагою буде: завершена попередня програма Genesis Academy, базовий Python або SQL, регулярний досвід з ChatGPT / Claude / Cursor.",
    },
    {
      q: "Чи треба мати ML / Data Science бекграунд?",
      a: "Ні. Профільна ML / Data Science освіта не вимагається. Ми приймаємо PM, аналітиків, маркетологів — за умови продуктового інтересу та готовності навчатись.",
    },
    {
      q: "Який формат участі в Challenge?",
      a: "Індивідуальний. Кожен учасник обирає один з трьох кейсів і будує власне AI-рішення. Це дозволяє чесно оцінити внесок кожного, спрощує комунікацію з менторами і дає персональний проєкт у портфоліо.",
    },
    {
      q: "Як працює fast-track на співбесіду?",
      a: "Топ-3 учасники після Demo Day отримують прямий fast-track до співбесід у Genesis-компанії, чий кейс вирішували. Журі — CPO/Head of Product компаній-замовників.",
    },
  ],
};
